name: DartWebServer
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Navoki <shivamsrivastava.9@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  http: ^0.12.0+2
  mysql1: ^0.17.0
